/* Kurzfragen für die Lernkartei: automatisch geprüft, mit Fehlerpunkten (p, 2 bis 5) wie in der Fahrschule.
   t: 'mc' (Standard, eine oder mehrere Antworten richtig) oder 'num' (Zahl oder Bruch eintippen).
   o: [Antwort, richtig?]. why: Erklärung nach dem Abgeben. tip: Hinweis vor dem Abgeben. */
KQ.push(
/* ---------- Lernbereich 1: Graph ---------- */
{ id: 'k1-01', m: 1, p: 3, q: String.raw`Was ergibt \(\sqrt{(x-2)^2}\)?`,
  o: [[String.raw`\(|x-2|\)`, 1], [String.raw`\(x-2\)`, 0], [String.raw`\(2-x\)`, 0], [String.raw`\(\pm(x-2)\)`, 0]],
  tip: String.raw`Setz \(x = 0\) ein und vergleiche.`,
  why: String.raw`\(\sqrt{a^2} = |a|\). Die Wurzel ist nie negativ, \(x-2\) aber schon, zum Beispiel für \(x = 0\).` },
{ id: 'k1-02', m: 1, p: 2, q: String.raw`Aus dem Graphen von \(g(x)\) wird der Graph von \(g(x-3)\). Was passiert?`,
  o: [['um 3 nach rechts', 1], ['um 3 nach links', 0], ['um 3 nach oben', 0], ['um 3 nach unten', 0]],
  why: String.raw`Was in der Klammer bei \(x\) passiert, wirkt umgekehrt. Der Punkt, der vorher bei \(x = 0\) lag, liegt jetzt bei \(x = 3\).` },
{ id: 'k1-03', m: 1, p: 3, q: String.raw`\(f(x) = -|x+1| + 2\). Welche Aussagen stimmen?`,
  o: [[String.raw`Die Spitze liegt bei \((-1\,|\,2)\).`, 1], ['Der Graph ist ein umgedrehtes V, die Spitze zeigt nach oben.', 1], [String.raw`Die Spitze liegt bei \((1\,|\,2)\).`, 0], [String.raw`\(y = 2\) ist eine Asymptote.`, 0]],
  why: String.raw`\(x+1\) schiebt um 1 nach links, \(+2\) um 2 nach oben, das Minus vorne klappt das V um. Beträge haben keine Asymptoten.` },
{ id: 'k1-04', m: 1, p: 3, q: String.raw`Welcher Definitionsbereich gehört zu \(f(x) = \sqrt{3-x} + 1\)?`,
  o: [[String.raw`\((-\infty, 3]\)`, 1], [String.raw`\([3, \infty)\)`, 0], [String.raw`\((-\infty, 3)\)`, 0], [String.raw`\(\mathbb R\)`, 0]],
  why: String.raw`Unter der Wurzel \(\ge 0\): \(3 - x \ge 0 \iff x \le 3\). Die 3 gehört dazu, weil \(\sqrt0 = 0\) erlaubt ist.` },
{ id: 'k1-05', m: 1, p: 3, q: String.raw`Welche Asymptoten hat \(f(x) = \frac{1}{x+2} + 1\)?`,
  o: [[String.raw`\(x = -2\)`, 1], [String.raw`\(y = 1\)`, 1], [String.raw`\(x = 2\)`, 0], [String.raw`\(y = 0\)`, 0]],
  why: String.raw`Hyperbel \(\frac1x\), um 2 nach links und 1 nach oben. Beide Asymptoten wandern mit: \(x = 0\) wird \(x = -2\), \(y = 0\) wird \(y = 1\).` },
{ id: 'k1-06', m: 1, p: 4, q: String.raw`\(f(x) = \frac{x-2}{x^2-4} - 1\). Was liegt bei \(x = 2\) vor?`,
  o: [[String.raw`eine hebbare Lücke, Loch bei \(\left(2\,|\,-\frac34\right)\)`, 1], [String.raw`eine Polstelle mit Asymptote \(x = 2\)`, 0], ['eine Nullstelle', 0], [String.raw`nichts, \(f(2)\) ist definiert`, 0]],
  tip: String.raw`\(x^2 - 4 = (x-2)(x+2)\).`,
  why: String.raw`Der Faktor \(x - 2\) kürzt sich weg, es bleibt \(\frac1{x+2} - 1\). Bei 2 wäre das \(\frac14 - 1 = -\frac34\), aber 2 liegt nicht in \(D\). Also ein offener Kreis. Nov 2020.` },
{ id: 'k1-07', m: 1, p: 2, q: 'Wann bestimmst du den Definitionsbereich?',
  o: [['an der Originalfunktion, bevor du kürzt oder quadrierst', 1], ['nach dem Vereinfachen, dann ist es übersichtlicher', 0], ['nur wenn die Aufgabe ausdrücklich danach fragt', 0], ['am Ende anhand der Skizze', 0]],
  why: String.raw`Nach dem Kürzen sieht man eine Lücke nicht mehr, sie ist aber trotzdem da. In Sep 2024 fehlt sonst \(x = 0\).` },
{ id: 'k1-08', m: 1, p: 4, q: String.raw`Welche Funktionen haben die waagerechte Asymptote \(y = -3\)?`,
  o: [[String.raw`\(2^x - 3\)`, 1], [String.raw`\(\frac1x - 3\)`, 1], [String.raw`\(\sqrt x - 3\)`, 0], [String.raw`\((x-3)^2\)`, 0]],
  why: String.raw`\(2^x\) geht für \(x \to -\infty\) gegen 0, \(\frac1x\) für \(x \to \pm\infty\) auch. Minus 3 schiebt die Asymptote \(y = 0\) nach \(y = -3\). \(\sqrt x\) und die Parabel wachsen immer weiter.` },
{ id: 'k1-09', m: 1, p: 3, q: String.raw`\(\sin(x - \pi)\) ist gleich …`,
  o: [[String.raw`\(-\sin x\)`, 1], [String.raw`\(\sin x\)`, 0], [String.raw`\(\cos x\)`, 0], [String.raw`\(-\cos x\)`, 0]],
  why: String.raw`Eine halbe Umdrehung dreht das Vorzeichen. Juli 2022: \(2\sin(x - \pi) + 2 = 2 - 2\sin x\).` },
{ id: 'k1-10', m: 1, p: 2, q: 'Wie zeichnest du eine hebbare Lücke in den Graphen?',
  o: [['als offenen Kreis', 1], ['als vollen Punkt', 0], ['als gestrichelte senkrechte Linie', 0], ['gar nicht, man sieht sie nicht', 0]],
  why: 'Offener Kreis heißt: Hier fehlt genau ein Punkt. Ein voller Punkt markiert einen Randpunkt, der dazugehört. Gestrichelt sind Asymptoten.' },
{ id: 'k1-11', m: 1, p: 5, q: String.raw`\(f(x) = \left(\sqrt{-\frac x2 + 1}\right)^2 - 3\). Wie sieht der Graph aus?`,
  o: [[String.raw`halbe Gerade mit Steigung \(-\frac12\), endet bei \((2\,|\,-3)\) mit vollem Punkt`, 1], [String.raw`ganze Gerade \(y = -\frac x2 - 2\)`, 0], [String.raw`Wurzelkurve, die bei \((2\,|\,-3)\) startet`, 0], [String.raw`Parabel mit Scheitel \((2\,|\,-3)\)`, 0]],
  tip: 'Das Quadrat hebt die Wurzel auf. Was bleibt vom Definitionsbereich?',
  why: String.raw`Es bleibt \(-\frac x2 + 1 - 3 = -\frac x2 - 2\). Der Definitionsbereich der Wurzel gilt aber weiter: \(-\frac x2 + 1 \ge 0 \iff x \le 2\). Deshalb nur die halbe Gerade. Vorbild: Feb 2022.` },
{ id: 'k1-12', m: 1, p: 4, q: String.raw`Wie entsteht \(\sqrt{-x+3}\) aus \(\sqrt x\)?`,
  o: [['an der y-Achse gespiegelt und um 3 nach rechts geschoben', 1], ['an der y-Achse gespiegelt und um 3 nach links geschoben', 0], ['an der x-Achse gespiegelt und um 3 nach oben geschoben', 0], ['nur um 3 nach rechts geschoben', 0]],
  why: String.raw`Minus ausklammern: \(\sqrt{-x+3} = \sqrt{-(x-3)}\). \(-x\) spiegelt an der y-Achse, \(x - 3\) schiebt um 3 nach rechts. Start bei \(x = 3\), von dort läuft die Kurve nach links. Dez 2023.` },
{ id: 'k1-13', m: 1, p: 3, q: String.raw`Welche Nullstellen hat \(f(x) = (x-1)^2 - 4\)?`,
  o: [[String.raw`\(x = -1\) und \(x = 3\)`, 1], [String.raw`\(x = 1\) und \(x = -4\)`, 0], [String.raw`nur \(x = 3\)`, 0], [String.raw`\(x = -3\) und \(x = 1\)`, 0]],
  why: String.raw`\((x-1)^2 = 4 \iff x - 1 = 2\) oder \(x - 1 = -2\). Die zweite Lösung vergisst man, wenn man nur die Wurzel zieht. Feb 2023.` },
{ id: 'k1-14', m: 1, p: 4, q: String.raw`Welchen Wertebereich hat \(f(x) = 1 - e^{-x+2}\)?`,
  o: [[String.raw`\((-\infty, 1)\)`, 1], [String.raw`\((1, \infty)\)`, 0], [String.raw`\((-\infty, 1]\)`, 0], [String.raw`\(\mathbb R\)`, 0]],
  why: String.raw`\(e^{-x+2}\) ist immer positiv, also ist \(1 - e^{-x+2}\) immer kleiner als 1. Die 1 selbst wird nie erreicht, sie ist die Asymptote. Juli 2021.` },

/* ---------- Lernbereich 2: Betrag ---------- */
{ id: 'k2-01', m: 2, p: 2, q: String.raw`Welche Lösungen hat \(|x-2| = 3\)?`,
  o: [[String.raw`\(\{-1,\ 5\}\)`, 1], [String.raw`\(\{5\}\)`, 0], [String.raw`\(\{1,\ 5\}\)`, 0], [String.raw`\(\{-5,\ 1\}\)`, 0]],
  why: String.raw`\(|A| = 3\) heißt \(A = 3\) oder \(A = -3\): \(x - 2 = 3 \Rightarrow x = 5\), \(x - 2 = -3 \Rightarrow x = -1\).` },
{ id: 'k2-02', m: 2, p: 2, q: String.raw`Welche Lösungsmenge hat \(|2x+1| = -4\)?`,
  o: [[String.raw`\(\emptyset\)`, 1], [String.raw`\(\left\{-\frac52,\ \frac32\right\}\)`, 0], [String.raw`\(\left\{\frac32\right\}\)`, 0], [String.raw`\(\left\{-\frac52\right\}\)`, 0]],
  why: String.raw`Ein Betrag ist nie negativ. Rechts steht \(-4\), also gibt es keine Lösung.` },
{ id: 'k2-03', m: 2, p: 3, q: String.raw`Welche Knickstellen hat die Gleichung \(-2|x-2| = |-3x+1| - 40\)?`,
  o: [[String.raw`\(x = 2\) und \(x = \frac13\)`, 1], [String.raw`\(x = -2\) und \(x = \frac13\)`, 0], [String.raw`\(x = 2\) und \(x = -\frac13\)`, 0], [String.raw`\(x = 2\) und \(x = 40\)`, 0]],
  why: String.raw`Knickstelle heißt: Inhalt des Betrags gleich 0. \(x - 2 = 0 \Rightarrow x = 2\) und \(-3x + 1 = 0 \Rightarrow x = \frac13\). Juli 2023.` },
{ id: 'k2-04', m: 2, p: 2, t: 'num', q: 'Wie viele Fälle unterscheidest du bei zwei verschiedenen Knickstellen?', a: 3, show: '3',
  why: 'Zwei Knickstellen zerschneiden den Zahlenstrahl in drei Bereiche: links, Mitte, rechts.' },
{ id: 'k2-05', m: 2, p: 3, q: String.raw`Für \(x \lt \frac13\): Wie schreibst du \(|-3x+1|\) ohne Betragsstriche?`,
  o: [[String.raw`\(-3x+1\)`, 1], [String.raw`\(3x-1\)`, 0], [String.raw`\(3x+1\)`, 0], [String.raw`\(-3x-1\)`, 0]],
  tip: String.raw`Setz einen Testwert aus dem Bereich ein, zum Beispiel \(x = 0\).`,
  why: String.raw`Testwert \(x = 0\): \(-3\cdot0 + 1 = 1 \gt 0\). Der Inhalt ist positiv, die Striche fallen einfach weg.` },
{ id: 'k2-06', m: 2, p: 3, q: String.raw`Für \(x \lt 2\): Wie schreibst du \(|x-2|\) ohne Betragsstriche?`,
  o: [[String.raw`\(2-x\)`, 1], [String.raw`\(x-2\)`, 0], [String.raw`\(-x-2\)`, 0], [String.raw`\(x+2\)`, 0]],
  why: String.raw`Testwert \(x = 0\): \(0 - 2 = -2 \lt 0\). Negativer Inhalt, also \(|x-2| = -(x-2) = 2 - x\).` },
{ id: 'k2-07', m: 2, p: 3, q: String.raw`Im Fall \(\frac13 \le x \lt 2\) kommt \(x = 37\) heraus. Was machst du damit?`,
  o: [['streichen, weil 37 nicht im Bereich dieses Falls liegt', 1], ['als Lösung in die Lösungsmenge schreiben', 0], ['die Rechnung verwerfen, da muss ein Fehler sein', 0], ['in Fall 3 als Lösung übernehmen', 0]],
  why: 'Jede Lösung gilt nur für ihren eigenen Bereich. Dass eine Zahl außerhalb herauskommt, ist normal und kein Rechenfehler.' },
{ id: 'k2-08', m: 2, p: 4, q: String.raw`\((7 - \sqrt a)^2 = \) ?`,
  o: [[String.raw`\(49 - 14\sqrt a + a\)`, 1], [String.raw`\(49 - a\)`, 0], [String.raw`\(49 + a\)`, 0], [String.raw`\(49 - 7\sqrt a + a\)`, 0]],
  why: String.raw`Zweite binomische Formel: \((p - q)^2 = p^2 - 2pq + q^2\) mit \(p = 7\), \(q = \sqrt a\). Wer \(49 - a\) schreibt, verliert in Juli 2022 die ganze Aufgabe.` },
{ id: 'k2-09', m: 2, p: 2, q: 'Warum ist nach dem Quadrieren einer Gleichung die Probe Pflicht?',
  o: [['Quadrieren kann Scheinlösungen erzeugen.', 1], ['Quadrieren kann echte Lösungen löschen.', 0], ['Die Probe ersetzt den Definitionsbereich.', 0], ['Die Probe braucht man nur bei Ungleichungen.', 0]],
  why: String.raw`\((-3)^2 = 3^2\): Nach dem Quadrieren erfüllen auch Zahlen die Gleichung, die vorher nicht passten. In Sep 2024 (Aufgabe 3) war \(x = 6\) so eine Scheinlösung.` },
{ id: 'k2-10', m: 2, p: 3, q: String.raw`\(-3x \le 6\) ist gleichbedeutend mit …`,
  o: [[String.raw`\(x \ge -2\)`, 1], [String.raw`\(x \le -2\)`, 0], [String.raw`\(x \ge 2\)`, 0], [String.raw`\(x \le 2\)`, 0]],
  why: String.raw`Durch \(-3\) teilen dreht das Zeichen: \(\le\) wird \(\ge\). Und \(6 : (-3) = -2\).` },
{ id: 'k2-11', m: 2, p: 4, q: String.raw`Welche Lösungsmenge hat \(x^2 \ge 3\)?`,
  o: [[String.raw`\((-\infty, -\sqrt3\,] \cup [\sqrt3, \infty)\)`, 1], [String.raw`\([-\sqrt3, \sqrt3]\)`, 0], [String.raw`\([\sqrt3, \infty)\)`, 0], [String.raw`\((-\infty, -\sqrt3) \cup (\sqrt3, \infty)\)`, 0]],
  why: String.raw`\(x^2 \ge 3 \iff |x| \ge \sqrt3\), also zwei Äste. Eckige Klammern, weil \(\pm\sqrt3\) selbst passen: \(3 \ge 3\). Dez 2023.` },
{ id: 'k2-12', m: 2, p: 4, q: String.raw`\(|-3x+6| = 1 + c\). Für welche \(c\) gibt es keine Lösung?`,
  o: [[String.raw`\(c \lt -1\)`, 1], [String.raw`\(c \gt -1\)`, 0], [String.raw`\(c = -1\)`, 0], [String.raw`\(c \lt 0\)`, 0]],
  why: String.raw`Ein Betrag ist nie negativ. Keine Lösung, wenn rechts etwas Negatives steht: \(1 + c \lt 0 \iff c \lt -1\). Bei \(c = -1\) gibt es genau eine Lösung. Feb 2023.` },
{ id: 'k2-13', m: 2, p: 5, q: String.raw`Welche Lösungsmenge hat \(\dfrac{|x^2-5| - 11}{|x+4|} = 0\)?`,
  o: [[String.raw`\(\{4\}\)`, 1], [String.raw`\(\{-4,\ 4\}\)`, 0], [String.raw`\(\{-4\}\)`, 0], [String.raw`\(\emptyset\)`, 0]],
  tip: 'Ein Bruch ist 0, wenn der Zähler 0 ist und der Nenner nicht.',
  why: String.raw`Zähler 0: \(|x^2 - 5| = 11 \Rightarrow x^2 = 16\), die andere Möglichkeit \(x^2 = -6\) geht nicht. Also \(\pm4\). Bei \(x = -4\) ist aber der Nenner 0, das fliegt raus. Feb 2022.` },
{ id: 'k2-14', m: 2, p: 3, q: String.raw`\(|-3x-6| = \) ?`,
  o: [[String.raw`\(3\,|x+2|\)`, 1], [String.raw`\(-3\,|x+2|\)`, 0], [String.raw`\(3\,|x-2|\)`, 0], [String.raw`\(|3x-6|\)`, 0]],
  why: String.raw`\(-3x - 6 = -3(x+2)\). Der Betrag schluckt das Minus, der Faktor kommt raus: \(|-3|\cdot|x+2| = 3|x+2|\). Juli 2022.` },
{ id: 'k2-15', m: 2, p: 4, q: String.raw`Welchen Definitionsbereich hat die Gleichung \(\dfrac{2x-5}{|x-2|} = |x-4|\)?`,
  o: [[String.raw`\(\mathbb R\setminus\{2\}\)`, 1], [String.raw`\(\mathbb R\setminus\{2,\ 4\}\)`, 0], [String.raw`\(\mathbb R\)`, 0], [String.raw`\((2, \infty)\)`, 0]],
  why: String.raw`Nur der Nenner \(|x-2|\) darf nicht 0 werden. \(|x-4|\) steht nicht im Nenner. Sep 2021.` },

/* ---------- Lernbereich 3: Brüche ---------- */
{ id: 'k3-01', m: 3, p: 2, q: String.raw`\((a+b)^{-1} = \) ?`,
  o: [[String.raw`\(\frac{1}{a+b}\)`, 1], [String.raw`\(\frac1a + \frac1b\)`, 0], [String.raw`\(-(a+b)\)`, 0], [String.raw`\(a^{-1}\cdot b^{-1}\)`, 0]],
  why: String.raw`Hoch \(-1\) heißt Kehrwert des Ganzen. Probe mit \(a = b = 1\): links \(\frac12\), bei \(\frac1a + \frac1b\) käme 2 heraus.` },
{ id: 'k3-02', m: 3, p: 3, q: String.raw`\(\dfrac{4}{\frac1x + 2}\) vereinfacht ergibt …`,
  o: [[String.raw`\(\frac{4x}{1+2x}\)`, 1], [String.raw`\(4x + 2\)`, 0], [String.raw`\(\frac{4}{1+2x}\)`, 0], [String.raw`\(2x\)`, 0]],
  why: String.raw`Zähler und Nenner mit \(x\) malnehmen: \(\frac{4\cdot x}{\left(\frac1x + 2\right)\cdot x} = \frac{4x}{1 + 2x}\). Okt 2020.` },
{ id: 'k3-03', m: 3, p: 2, q: String.raw`Nach dem Kürzen ist der Faktor \((x - x_0)\) ganz aus dem Nenner verschwunden. Was liegt bei \(x_0\) vor?`,
  o: [['eine hebbare Lücke', 1], ['eine Polstelle mit Vorzeichenwechsel', 0], ['eine Polstelle ohne Vorzeichenwechsel', 0], ['eine Nullstelle', 0]],
  why: String.raw`Die Stelle fehlt in \(D\), aber die gekürzte Funktion hat dort einen normalen Wert. Im Graphen ein Loch.` },
{ id: 'k3-04', m: 3, p: 3, q: String.raw`Nach dem Kürzen bleibt \((x-2)^2\) im Nenner, und der Zähler ist bei 2 nicht 0. Was liegt bei \(x = 2\) vor?`,
  o: [['eine Polstelle ohne Vorzeichenwechsel', 1], ['eine Polstelle mit Vorzeichenwechsel', 0], ['eine hebbare Lücke', 0], ['eine Nullstelle', 0]],
  why: 'Gerade Potenz im Nenner: Das Quadrat ist links und rechts von 2 positiv, beide Äste laufen in dieselbe Richtung. Nov 2025, Aufgabe 3.' },
{ id: 'k3-05', m: 3, p: 4, q: String.raw`\(f(x) = \dfrac{x^2 - x - 6}{x^2 + 4x + 4}\). Was liegt bei \(x = -2\) vor?`,
  o: [['eine Polstelle mit Vorzeichenwechsel', 1], ['eine Polstelle ohne Vorzeichenwechsel', 0], ['eine hebbare Lücke', 0], ['eine Nullstelle', 0]],
  tip: 'Erst Zähler und Nenner faktorisieren, dann kürzen.',
  why: String.raw`\(\frac{(x-3)(x+2)}{(x+2)^2} = \frac{x-3}{x+2}\). Es bleibt \((x+2)^1\), ungerade Potenz, also mit Vorzeichenwechsel. Vor dem Kürzen sieht der Nenner nach Quadrat aus. Feb 2023.` },
{ id: 'k3-06', m: 3, p: 3, q: String.raw`Welche Asymptote hat \(\dfrac{4x^2 - 36}{x^2 - 4x + 4}\) für \(x \to \pm\infty\)?`,
  o: [[String.raw`\(y = 4\)`, 1], [String.raw`\(y = 0\)`, 0], [String.raw`\(y = 4x\)`, 0], ['keine', 0]],
  why: String.raw`Zählergrad und Nennergrad sind beide 2. Dann ist die Asymptote das Verhältnis der Vorfaktoren: \(\frac41 = 4\).` },
{ id: 'k3-07', m: 3, p: 2, q: String.raw`Zählergrad 2, Nennergrad 3. Welche Asymptote gibt es für \(x \to \pm\infty\)?`,
  o: [[String.raw`\(y = 0\)`, 1], [String.raw`\(y = 1\)`, 0], ['eine schiefe Asymptote', 0], ['keine', 0]],
  why: 'Der Nenner wächst schneller als der Zähler, der Bruch geht gegen 0.' },
{ id: 'k3-08', m: 3, p: 4, q: String.raw`\((x^2 - x - 5) : (x - 3) = \) ?`,
  o: [[String.raw`\(x + 2\), Rest \(1\)`, 1], [String.raw`\(x + 2\), ohne Rest`, 0], [String.raw`\(x - 4\), Rest \(7\)`, 0], [String.raw`\(x + 2\), Rest \(-1\)`, 0]],
  why: String.raw`\((x-3)(x+2) = x^2 - x - 6\). Bis \(x^2 - x - 5\) fehlt noch 1, das ist der Rest. Also \(x + 2 + \frac1{x-3}\), schiefe Asymptote \(y = x + 2\). Nov 2024.` },
{ id: 'k3-09', m: 3, p: 2, t: 'num', q: String.raw`\(-3^2 = \) ?`, a: -9, show: '−9',
  why: String.raw`Erst die Potenz, dann das Minus: \(-(3^2) = -9\). Dez 2023: \(-3^2\cdot\frac{x-3}{x^2-9}\).` },
{ id: 'k3-10', m: 3, p: 3, q: String.raw`\(f(x) = x\left(\frac{4}{2x+1} - \frac{1}{4x+1}\right)\) mit \(D = \mathbb R\setminus\left\{-\frac12, -\frac14, 0\right\}\). Ist \(x = 0\) eine Nullstelle?`,
  o: [[String.raw`nein, weil 0 nicht in \(D\) liegt`, 1], [String.raw`ja, wegen des Faktors \(x\)`, 0], ['ja, aber nur eine doppelte', 0], ['nur wenn die Klammer auch 0 ist', 0]],
  why: String.raw`Nullstellen müssen in \(D\) liegen. Die 0 flog schon wegen \(x^{-1}\) in der Originalfunktion raus. Okt 2020.` },
{ id: 'k3-11', m: 3, p: 4, q: String.raw`Welchen Definitionsbereich hat \(f(x) = \dfrac{4}{x^{-1} + 2}\)?`,
  o: [[String.raw`\(\mathbb R\setminus\left\{-\frac12,\ 0\right\}\)`, 1], [String.raw`\(\mathbb R\setminus\{0\}\)`, 0], [String.raw`\(\mathbb R\setminus\left\{-\frac12\right\}\)`, 0], [String.raw`\(\mathbb R\setminus\{-2,\ 0\}\)`, 0]],
  why: String.raw`Zwei Nenner: \(x^{-1} = \frac1x\) braucht \(x \ne 0\), und \(\frac1x + 2 \ne 0 \iff x \ne -\frac12\). Die inneren Nenner vergisst man am leichtesten.` },
{ id: 'k3-12', m: 3, p: 2, q: String.raw`Bei der Nullstellensuche steht \(x^3 - 4x = 0\) da. Was machst du?`,
  o: [[String.raw`\(x\) ausklammern: \(x(x^2 - 4) = 0\)`, 1], [String.raw`durch \(x\) teilen: \(x^2 - 4 = 0\)`, 0], [String.raw`mit \(x\) malnehmen`, 0], ['direkt die pq-Formel anwenden', 0]],
  why: String.raw`Durch \(x\) teilen verliert die Lösung \(x = 0\). Ausklammern behält sie: \(x = 0\) oder \(x = \pm2\).` },
{ id: 'k3-13', m: 3, p: 5, q: String.raw`Welche Werte nimmt \(\dfrac{1}{\sqrt{x^2+4}}\) an?`,
  o: [[String.raw`\(\left(0,\ \frac12\right]\)`, 1], [String.raw`\(\left[0,\ \frac12\right]\)`, 0], [String.raw`\((0,\ \infty)\)`, 0], [String.raw`\(\left[\frac12,\ \infty\right)\)`, 0]],
  why: String.raw`\(\sqrt{x^2+4} \ge 2\), am kleinsten bei \(x = 0\). Der Kehrwert ist also höchstens \(\frac12\), immer positiv und erreicht nie 0. Okt 2020: Nullstellen von \(\frac{1}{\sqrt{x^2+4}} - k\) gibt es nur für \(0 \lt k \le \frac12\).` },
{ id: 'k3-14', m: 3, p: 3, q: String.raw`Bei \(x = 1\) sind Zähler und Nenner eines Bruchs beide 0. Ist die Funktion dort definiert?`,
  o: [[String.raw`nein, \(\frac00\) ist nicht definiert`, 1], ['ja, der Wert ist 1', 0], ['ja, der Wert ist 0', 0], ['ja, wenn man vorher kürzt', 0]],
  why: String.raw`\(D\) wird an der Originalfunktion bestimmt, und dort steht \(\frac00\). Kürzen verrät nur die Art der Lücke, hier hebbar. Juli 2021.` },
{ id: 'k3-15', m: 3, p: 3, q: String.raw`\(\left(\frac1x + \frac1{c^2}\right)^{-1} = \) ?`,
  o: [[String.raw`\(\frac{xc^2}{c^2 + x}\)`, 1], [String.raw`\(x + c^2\)`, 0], [String.raw`\(\frac{c^2 + x}{xc^2}\)`, 0], [String.raw`\(\frac{1}{x + c^2}\)`, 0]],
  why: String.raw`Erst der Hauptnenner: \(\frac{c^2 + x}{xc^2}\). Hoch \(-1\) dreht den Bruch um. Nov 2022.` },

/* ---------- Lernbereich 4: Logarithmus ---------- */
{ id: 'k4-01', m: 4, p: 2, q: String.raw`\(\ln(a\cdot b) = \) ? (für \(a, b \gt 0\))`,
  o: [[String.raw`\(\ln a + \ln b\)`, 1], [String.raw`\(\ln a \cdot \ln b\)`, 0], [String.raw`\(\ln(a + b)\)`, 0], [String.raw`\(a\ln b\)`, 0]],
  why: 'Mal im Argument wird Plus vor dem Logarithmus.' },
{ id: 'k4-02', m: 4, p: 4, q: String.raw`Welche Gleichungen stimmen für \(a, b \gt 0\)?`,
  o: [[String.raw`\(\ln(a^2) = 2\ln a\)`, 1], [String.raw`\(\ln\frac ab = \ln a - \ln b\)`, 1], [String.raw`\(\ln(a+b) = \ln a + \ln b\)`, 0], [String.raw`\(\frac{\ln a}{\ln b} = \ln\frac ab\)`, 0]],
  why: 'Die Gesetze gelten für Produkt, Quotient und Potenz im Argument. Für eine Summe im Argument gibt es keine Regel, und ein Bruch aus zwei Logarithmen lässt sich nicht zusammenziehen.' },
{ id: 'k4-03', m: 4, p: 2, t: 'num', q: String.raw`\(\lg(1000) = \) ?`, a: 3, show: '3', why: String.raw`\(10^3 = 1000\).` },
{ id: 'k4-04', m: 4, p: 2, t: 'num', q: String.raw`\(\log_2(8) = \) ?`, a: 3, show: '3', why: String.raw`\(2^3 = 8\).` },
{ id: 'k4-05', m: 4, p: 3, q: String.raw`\(\log_5\left(25^{2x}\right) = \) ?`,
  o: [[String.raw`\(4x\)`, 1], [String.raw`\(2x\)`, 0], [String.raw`\(10x\)`, 0], [String.raw`\(50x\)`, 0]],
  why: String.raw`\(25 = 5^2\), also \(25^{2x} = 5^{4x}\). Der Logarithmus zur Basis 5 holt die Hochzahl raus. Sep 2021.` },
{ id: 'k4-06', m: 4, p: 4, q: String.raw`Welchen Definitionsbereich hat \(f(x) = \dfrac{1}{\ln(x-3)}\)?`,
  o: [[String.raw`\((3, 4) \cup (4, \infty)\)`, 1], [String.raw`\((3, \infty)\)`, 0], [String.raw`\([3, \infty)\setminus\{4\}\)`, 0], [String.raw`\((4, \infty)\)`, 0]],
  why: String.raw`Argument \(\gt 0\): \(x \gt 3\). Logarithmus im Nenner \(\ne 0\): \(x - 3 \ne 1\), also \(x \ne 4\). Okt 2020.` },
{ id: 'k4-07', m: 4, p: 3, q: String.raw`\(\ln x + \ln(x+6) = \ln 7\) liefert die Kandidaten \(x = 1\) und \(x = -7\). Wie lautet die Lösungsmenge?`,
  o: [[String.raw`\(\{1\}\)`, 1], [String.raw`\(\{-7,\ 1\}\)`, 0], [String.raw`\(\{-7\}\)`, 0], [String.raw`\(\emptyset\)`, 0]],
  why: String.raw`\(D\): \(x \gt 0\). \(-7\) liegt nicht drin, obwohl es die quadratische Gleichung löst. Okt 2020.` },
{ id: 'k4-08', m: 4, p: 2, q: String.raw`\(\ln A = c\). Dann ist \(A = \) ?`,
  o: [[String.raw`\(e^c\)`, 1], [String.raw`\(10^c\)`, 0], [String.raw`\(\ln c\)`, 0], [String.raw`\(c^e\)`, 0]],
  why: String.raw`\(e\) hoch auf beiden Seiten: \(e^{\ln A} = A\). Beim \(\lg\) wäre es \(10^c\).` },
{ id: 'k4-09', m: 4, p: 2, t: 'num', q: String.raw`\(\lg A = 2\). Wie groß ist \(A\)?`, a: 100, show: '100', why: String.raw`\(A = 10^2 = 100\).` },
{ id: 'k4-10', m: 4, p: 3, q: String.raw`\(2\log_4|x| = \) ?`,
  o: [[String.raw`\(\log_4(x^2)\)`, 1], [String.raw`\(\log_4(2x)\)`, 0], [String.raw`\((\log_4 x)^2\)`, 0], [String.raw`\(\log_{16}|x|\)`, 0]],
  why: String.raw`Faktor wird Hochzahl: \(2\log_4|x| = \log_4(|x|^2)\), und \(|x|^2 = x^2\). Juli 2022.` },
{ id: 'k4-11', m: 4, p: 2, q: 'In Aufgabe 4 lautet die Antwort auffällig oft „keine Lösung“. Woran liegt das meistens?',
  o: [['Der einzige Kandidat liegt nicht im Definitionsbereich.', 1], ['Die quadratische Gleichung hat keine reelle Lösung.', 0], ['Logarithmen werden nie 0.', 0], ['Man hat sich verrechnet.', 0]],
  why: String.raw`Das ist Absicht des Prüfers. Deshalb am Ende jede Lösung gegen \(D\) prüfen. Nov 2022: Kandidat \(x \approx -7{,}4\), aber \(D = (4, \infty)\).` },
{ id: 'k4-12', m: 4, p: 2, q: 'Welche Schreibweise der Zahl 1 hilft, eine Logarithmusgleichung zusammenzufassen?',
  o: [[String.raw`\(\ln e\)`, 1], [String.raw`\(\ln 1\)`, 0], [String.raw`\(\lg 1\)`, 0], [String.raw`\(\ln 10\)`, 0]],
  why: String.raw`\(\ln e = 1\). So wird aus \(\ln(x-1) + 1\) der Ausdruck \(\ln\big(e(x-1)\big)\). \(\ln 1\) und \(\lg 1\) sind 0.` },
{ id: 'k4-13', m: 4, p: 3, q: String.raw`\(\ln\sqrt x = \) ?`,
  o: [[String.raw`\(\frac12\ln x\)`, 1], [String.raw`\(\sqrt{\ln x}\)`, 0], [String.raw`\(2\ln x\)`, 0], [String.raw`\(\frac{\ln x}{2x}\)`, 0]],
  why: String.raw`\(\sqrt x = x^{1/2}\), die Hochzahl kommt nach vorne.` },
{ id: 'k4-14', m: 4, p: 5, q: String.raw`Welche Lösung hat \(\sqrt{\ln(x+1) - \ln x} = 2\)?`,
  o: [[String.raw`\(x = \frac1{e^4 - 1}\)`, 1], [String.raw`\(x = \frac1{e^2 - 1}\)`, 0], [String.raw`\(x = e^4 - 1\)`, 0], ['keine Lösung', 0]],
  why: String.raw`Quadrieren: \(\ln\frac{x+1}x = 4\), also \(\frac{x+1}x = e^4\). Dann \(x + 1 = e^4x \iff x(e^4 - 1) = 1\). Wer das Quadrieren vergisst, landet bei \(e^2\). Feb 2023.` },
{ id: 'k4-15', m: 4, p: 3, q: String.raw`Wo ist \(\ln|x|\) definiert?`,
  o: [[String.raw`für alle \(x \ne 0\)`, 1], [String.raw`für \(x \gt 0\)`, 0], [String.raw`für \(x \ge 0\)`, 0], [String.raw`für alle \(x\)`, 0]],
  why: String.raw`Der Betrag macht jedes \(x \ne 0\) positiv. Nur bei 0 ist das Argument 0.` },

/* ---------- Lernbereich 5: Trigonometrie ---------- */
{ id: 'k5-01', m: 5, p: 3, q: String.raw`\(\sin u = \frac12\). Welche zwei Lösungen gibt es in \([0, 2\pi)\)?`,
  o: [[String.raw`\(\frac\pi6\) und \(\frac{5\pi}6\)`, 1], [String.raw`\(\frac\pi6\) und \(-\frac\pi6\)`, 0], [String.raw`\(\frac\pi3\) und \(\frac{2\pi}3\)`, 0], [String.raw`nur \(\frac\pi6\)`, 0]],
  why: String.raw`Sinus: \(\alpha\) und \(\pi - \alpha\), also \(\pi - \frac\pi6 = \frac{5\pi}6\). Das \(\pm\alpha\) gehört zum Kosinus.` },
{ id: 'k5-02', m: 5, p: 3, q: String.raw`Welches sind alle Lösungen von \(\cos u = \frac12\)?`,
  o: [[String.raw`\(u = \pm\frac\pi3 + 2k\pi\)`, 1], [String.raw`\(u = \frac\pi3 + 2k\pi\)`, 0], [String.raw`\(u = \pm\frac\pi6 + 2k\pi\)`, 0], [String.raw`\(u = \frac\pi3 + k\pi\)`, 0]],
  why: String.raw`\(\cos\frac\pi3 = \frac12\). Der Kosinus ist symmetrisch, also \(\pm\). Periode \(2\pi\), also \(+2k\pi\).` },
{ id: 'k5-03', m: 5, p: 3, q: String.raw`Welche Lösungsmenge hat \(\sin(2x) = \frac{2\pi}3\)?`,
  o: [[String.raw`\(\emptyset\)`, 1], [String.raw`\(x = \frac\pi3 + k\pi\)`, 0], [String.raw`\(x = \frac\pi6 + k\pi\)`, 0], [String.raw`\(x = \frac\pi3\)`, 0]],
  why: String.raw`\(\frac{2\pi}3 \approx 2{,}09\). Ein Sinus kommt nie über 1. Dez 2023.` },
{ id: 'k5-04', m: 5, p: 4, q: String.raw`Bei welchen rechten Seiten \(a\) hat \(\cos(\dots) = a\) keine Lösung?`,
  o: [[String.raw`\(2\pi\)`, 1], [String.raw`\(e^9\)`, 1], [String.raw`\(\frac{1}{\pi^{-1}}\)`, 1], [String.raw`\(-\frac{\sqrt2}2\)`, 0]],
  why: String.raw`\(2\pi \approx 6{,}3\), \(e^9\) ist riesig, \(\frac1{\pi^{-1}} = \pi \approx 3{,}14\). Alle größer als 1. \(-\frac{\sqrt2}2 \approx -0{,}71\) liegt zwischen \(-1\) und 1.` },
{ id: 'k5-05', m: 5, p: 4, q: String.raw`\(2x - 1 = \pm\frac{2\pi}3 + 2k\pi\). Wie lautet \(x\)?`,
  o: [[String.raw`\(x = \frac12 \pm \frac\pi3 + k\pi\)`, 1], [String.raw`\(x = \frac12 \pm \frac\pi3 + 2k\pi\)`, 0], [String.raw`\(x = 1 \pm \frac{2\pi}3 + 2k\pi\)`, 0], [String.raw`\(x = \frac12 \pm \frac{2\pi}3 + k\pi\)`, 0]],
  why: String.raw`Plus 1, dann alles durch 2 teilen, auch die Periode: \(2k\pi : 2 = k\pi\). Nov 2022.` },
{ id: 'k5-06', m: 5, p: 2, q: 'Welche Periode hat der Tangens?',
  o: [[String.raw`\(\pi\)`, 1], [String.raw`\(2\pi\)`, 0], [String.raw`\(\frac\pi2\)`, 0], [String.raw`\(4\pi\)`, 0]],
  why: String.raw`Der Tangens wiederholt sich schon nach \(\pi\), deshalb \(u + k\pi\).` },
{ id: 'k5-07', m: 5, p: 2, q: String.raw`\(\sin u = 0 \iff\) ?`,
  o: [[String.raw`\(u = k\pi\)`, 1], [String.raw`\(u = \frac\pi2 + k\pi\)`, 0], [String.raw`\(u = 2k\pi\)`, 0], [String.raw`\(u = \frac\pi2 + 2k\pi\)`, 0]],
  why: String.raw`Der Sinus ist 0 bei \(0, \pi, 2\pi, \dots\) und bei \(-\pi, -2\pi, \dots\), also bei jedem Vielfachen von \(\pi\).` },
{ id: 'k5-08', m: 5, p: 2, q: String.raw`\(\cos u = 0 \iff\) ?`,
  o: [[String.raw`\(u = \frac\pi2 + k\pi\)`, 1], [String.raw`\(u = k\pi\)`, 0], [String.raw`\(u = 2k\pi\)`, 0], [String.raw`\(u = \pi + 2k\pi\)`, 0]],
  why: String.raw`Am Einheitskreis ist der x-Wert ganz oben und ganz unten 0, also bei \(\frac\pi2\) und \(\frac{3\pi}2\). Abstand \(\pi\).` },
{ id: 'k5-09', m: 5, p: 3, q: String.raw`\(\cos u = -\frac12 \iff\) ?`,
  o: [[String.raw`\(u = \pm\frac{2\pi}3 + 2k\pi\)`, 1], [String.raw`\(u = \pm\frac\pi3 + 2k\pi\)`, 0], [String.raw`\(u = \pm\frac{5\pi}6 + 2k\pi\)`, 0], [String.raw`\(u = -\frac\pi6 + 2k\pi\) oder \(u = \frac{7\pi}6 + 2k\pi\)`, 0]],
  why: String.raw`Grundwinkel \(\frac\pi3\). Für negatives \(a\) beim Kosinus: \(\pm(\pi - \alpha) = \pm\frac{2\pi}3\). Die letzte Antwort gehört zu \(\sin u = -\frac12\).` },
{ id: 'k5-10', m: 5, p: 4, q: String.raw`\(\sin u = -\frac{\sqrt3}2 \iff\) ?`,
  o: [[String.raw`\(u = -\frac\pi3 + 2k\pi\) oder \(u = \frac{4\pi}3 + 2k\pi\)`, 1], [String.raw`\(u = \pm\frac{5\pi}6 + 2k\pi\)`, 0], [String.raw`\(u = \frac\pi3 + 2k\pi\) oder \(u = \frac{2\pi}3 + 2k\pi\)`, 0], [String.raw`\(u = -\frac\pi6 + 2k\pi\) oder \(u = \frac{7\pi}6 + 2k\pi\)`, 0]],
  why: String.raw`Grundwinkel \(\frac\pi3\). Negativer Sinus: \(-\alpha\) und \(\pi + \alpha\), also \(-\frac\pi3\) und \(\frac{4\pi}3\). Nov 2020.` },
{ id: 'k5-11', m: 5, p: 4, q: String.raw`\(\frac x6 = \pm\frac{5\pi}6 + 2k\pi\). Wie lautet \(x\)?`,
  o: [[String.raw`\(x = \pm5\pi + 12k\pi\)`, 1], [String.raw`\(x = \pm5\pi + 2k\pi\)`, 0], [String.raw`\(x = \pm\frac{5\pi}{36} + \frac{k\pi}3\)`, 0], [String.raw`\(x = \pm5\pi + 6k\pi\)`, 0]],
  why: String.raw`Mal 6, auch die Periode: \(2k\pi\cdot6 = 12k\pi\). Sep 2024.` },
{ id: 'k5-12', m: 5, p: 3, q: String.raw`\(\tan u \cdot \cos u = \) ? (für \(\cos u \ne 0\))`,
  o: [[String.raw`\(\sin u\)`, 1], [String.raw`\(1\)`, 0], [String.raw`\(\cos^2 u\)`, 0], [String.raw`\(\tan^2 u\)`, 0]],
  why: String.raw`\(\tan u = \frac{\sin u}{\cos u}\), mal \(\cos u\) kürzt sich weg. Juli 2021.` },
{ id: 'k5-13', m: 5, p: 4, q: String.raw`\(f(x) = \dfrac{1}{\cos(4x) - 1}\). Wo ist \(f\) nicht definiert?`,
  o: [[String.raw`\(x = \frac{k\pi}2\)`, 1], [String.raw`\(x = \frac{k\pi}4\)`, 0], [String.raw`\(x = \frac\pi8 + \frac{k\pi}4\)`, 0], [String.raw`\(x = 2k\pi\)`, 0]],
  why: String.raw`\(\cos(4x) = 1 \iff 4x = 2k\pi \iff x = \frac{k\pi}2\). Juli 2023.` },
{ id: 'k5-14', m: 5, p: 3, t: 'num', q: String.raw`\(\cos\left(\frac{10\pi}3\right) = \) ?`, a: -1 / 2, show: '−1/2',
  why: String.raw`\(\frac{10\pi}3 - 2\pi = \frac{4\pi}3 = \pi + \frac\pi3\). Die halbe Umdrehung dreht das Vorzeichen: \(-\cos\frac\pi3 = -\frac12\). Feb 2023.` },
{ id: 'k5-15', m: 5, p: 2, q: 'Was kostet in Aufgabe 5 am häufigsten Punkte?',
  o: [['die vergessene zweite Lösung pro Umdrehung', 1], [String.raw`das fehlende \(+2k\pi\) mit \(k \in \mathbb Z\)`, 1], ['das Ergebnis als Bruch statt als Dezimalzahl', 0], ['Winkel im Bogenmaß statt in Grad', 0]],
  why: String.raw`Beides steht im Rezept: Sinus \(\alpha\) und \(\pi - \alpha\), Kosinus \(\pm\alpha\), jeweils \(+2k\pi\). Brüche und Bogenmaß sind in der Klausur richtig und erwünscht.` },

/* ---------- Lernbereich 6: Ableiten ---------- */
{ id: 'k6-01', m: 6, p: 2, q: String.raw`\(\left(e^{6x}\right)' = \) ?`,
  o: [[String.raw`\(6e^{6x}\)`, 1], [String.raw`\(e^{6x}\)`, 0], [String.raw`\(6x\,e^{6x}\)`, 0], [String.raw`\(\frac{e^{6x}}6\)`, 0]],
  why: String.raw`Kettenregel: äußere Ableitung \(e^{6x}\) mal innere Ableitung 6.` },
{ id: 'k6-02', m: 6, p: 3, q: String.raw`\(\left(\sqrt{x^2+1}\right)' = \) ?`,
  o: [[String.raw`\(\frac{x}{\sqrt{x^2+1}}\)`, 1], [String.raw`\(\frac{1}{2\sqrt{x^2+1}}\)`, 0], [String.raw`\(\frac{2x}{\sqrt{x^2+1}}\)`, 0], [String.raw`\(\sqrt{2x}\)`, 0]],
  why: String.raw`\(\frac{1}{2\sqrt{x^2+1}}\cdot 2x\), die 2 kürzt sich. Die zweite Antwort vergisst die innere Ableitung.` },
{ id: 'k6-03', m: 6, p: 3, q: String.raw`\(\left(\sin(x^2)\right)' = \) ?`,
  o: [[String.raw`\(2x\cos(x^2)\)`, 1], [String.raw`\(\cos(x^2)\)`, 0], [String.raw`\(\cos(2x)\)`, 0], [String.raw`\(-2x\cos(x^2)\)`, 0]],
  why: String.raw`Außen \(\cos(x^2)\), innen \(2x\).` },
{ id: 'k6-04', m: 6, p: 3, q: String.raw`\(\left(\ln(x^2)\right)' = \) ?`,
  o: [[String.raw`\(\frac2x\)`, 1], [String.raw`\(\frac1{x^2}\)`, 0], [String.raw`\(2x\ln x\)`, 0], [String.raw`\(\frac1{2x}\)`, 0]],
  why: String.raw`\(\frac1{x^2}\cdot 2x = \frac2x\). Sep 2024.` },
{ id: 'k6-05', m: 6, p: 3, q: String.raw`\(\left(\sqrt{1-x}\right)' = \) ?`,
  o: [[String.raw`\(-\frac{1}{2\sqrt{1-x}}\)`, 1], [String.raw`\(\frac{1}{2\sqrt{1-x}}\)`, 0], [String.raw`\(-\frac{\sqrt{1-x}}2\)`, 0], [String.raw`\(\frac{1}{\sqrt{1-x}}\)`, 0]],
  why: String.raw`Die innere Ableitung von \(1 - x\) ist \(-1\). Wird oft vergessen, Feb 2023.` },
{ id: 'k6-06', m: 6, p: 2, q: String.raw`Quotientenregel: \(\left(\frac uv\right)' = \) ?`,
  o: [[String.raw`\(\frac{u'v - uv'}{v^2}\)`, 1], [String.raw`\(\frac{uv' - u'v}{v^2}\)`, 0], [String.raw`\(\frac{u'}{v'}\)`, 0], [String.raw`\(\frac{u'v + uv'}{v^2}\)`, 0]],
  why: 'NAZ minus ZAN durch N-Quadrat: Nenner mal Ableitung Zähler minus Zähler mal Ableitung Nenner.' },
{ id: 'k6-07', m: 6, p: 3, q: String.raw`\(\left(\sin(10) + x^3\right)' = \) ?`,
  o: [[String.raw`\(3x^2\)`, 1], [String.raw`\(\cos(10) + 3x^2\)`, 0], [String.raw`\(\sin(10) + 3x^2\)`, 0], [String.raw`\(\cos(10)\cdot 3x^2\)`, 0]],
  why: String.raw`\(\sin(10)\) ist nur eine Zahl, die Ableitung ist 0. Feb 2026.` },
{ id: 'k6-08', m: 6, p: 3, q: String.raw`\(\left(x\cdot\ln a\right)'\) mit einer Konstanten \(a \gt 0\) ist …`,
  o: [[String.raw`\(\ln a\)`, 1], [String.raw`\(\frac1a\)`, 0], [String.raw`\(\frac xa\)`, 0], [String.raw`\(\ln a + \frac xa\)`, 0]],
  why: String.raw`\(\ln a\) ist ein konstanter Faktor, und \(x' = 1\). Nov 2024.` },
{ id: 'k6-09', m: 6, p: 2, q: String.raw`\(\left(\frac1x\right)' = \) ?`,
  o: [[String.raw`\(-\frac1{x^2}\)`, 1], [String.raw`\(\ln x\)`, 0], [String.raw`\(\frac1{x^2}\)`, 0], [String.raw`\(-\frac1x\)`, 0]],
  why: String.raw`\(x^{-1}\) abgeleitet: \(-1\cdot x^{-2}\). \(\ln x\) ist die Stammfunktion, nicht die Ableitung.` },
{ id: 'k6-10', m: 6, p: 3, q: 'Welche Ergebnisse darfst du laut Deckblatt so stehen lassen?',
  o: [[String.raw`\(\frac{2}{e^{2x}}\)`, 1], [String.raw`\(\frac{2}{9x^3 - x}\)`, 1], [String.raw`\(2e^{-2x}\)`, 0], [String.raw`\(\frac{2x^{-3}}{9 - x^{-2}}\)`, 0]],
  why: String.raw`Keine negativen Exponenten, keine Doppelbrüche. \(2e^{-2x}\) wird zu \(\frac2{e^{2x}}\), der Doppelbruch wird mit \(x^3\) erweitert. Nov 2020.` },
{ id: 'k6-11', m: 6, p: 4, q: String.raw`\(\left(\frac1v\right)' = \) ? (\(v\) hängt von \(x\) ab)`,
  o: [[String.raw`\(-\frac{v'}{v^2}\)`, 1], [String.raw`\(\frac1{v'}\)`, 0], [String.raw`\(-\frac1{v^2}\)`, 0], [String.raw`\(\frac{v'}{v^2}\)`, 0]],
  why: String.raw`Kettenregel mit \(v^{-1}\): \(-v^{-2}\cdot v'\). Okt 2020: \(\left(\frac1{e^{-2x}+1}\right)' = \frac{2e^{-2x}}{(e^{-2x}+1)^2}\).` },
{ id: 'k6-12', m: 6, p: 4, q: String.raw`\(\left(x\,e^{-2x}\right)' = \) ?`,
  o: [[String.raw`\(\frac{1-2x}{e^{2x}}\)`, 1], [String.raw`\(-2e^{-2x}\)`, 0], [String.raw`\(\frac{1+2x}{e^{2x}}\)`, 0], [String.raw`\(e^{-2x} - 2x\)`, 0]],
  why: String.raw`Produktregel: \(1\cdot e^{-2x} + x\cdot(-2e^{-2x}) = (1-2x)e^{-2x}\), dann ohne negativen Exponenten. Juli 2021.` },
{ id: 'k6-13', m: 6, p: 4, q: String.raw`\(\left(\frac{x}{4x-1}\right)' = \) ?`,
  o: [[String.raw`\(-\frac{1}{(4x-1)^2}\)`, 1], [String.raw`\(\frac{1}{(4x-1)^2}\)`, 0], [String.raw`\(\frac{8x-1}{(4x-1)^2}\)`, 0], [String.raw`\(\frac14\)`, 0]],
  why: String.raw`\(\frac{1\cdot(4x-1) - x\cdot4}{(4x-1)^2} = \frac{-1}{(4x-1)^2}\). Juli 2023.` },
{ id: 'k6-14', m: 6, p: 4, q: String.raw`Für welche \(x\) existiert die Ableitung von \(\sqrt{1-x}\)?`,
  o: [[String.raw`\(x \lt 1\)`, 1], [String.raw`\(x \le 1\)`, 0], [String.raw`\(x \gt 1\)`, 0], [String.raw`für alle \(x\)`, 0]],
  why: String.raw`Die Ableitung \(-\frac1{2\sqrt{1-x}}\) hat die Wurzel im Nenner. Bei \(x = 1\) stünde dort 0. Die Funktion selbst ist bei 1 noch definiert.` },
{ id: 'k6-15', m: 6, p: 5, q: String.raw`\(f(x) = \frac{\sin(e^x)}{x^2+1} + x\ln a\). Was ist \(f'(0)\)?`,
  o: [[String.raw`\(\cos(1) + \ln a\)`, 1], [String.raw`\(\cos(1)\)`, 0], [String.raw`\(1 + \ln a\)`, 0], [String.raw`\(\sin(1) + \ln a\)`, 0]],
  tip: String.raw`Setz früh \(x = 0\) ein: \(e^0 = 1\), und alles mit Faktor \(x\) wird 0.`,
  why: String.raw`Quotientenregel, dann \(x = 0\): Zähler \(e^0\cos(e^0)\cdot1 - 0 = \cos 1\), Nenner 1. Dazu \(\ln a\). Nov 2024.` },

/* ---------- Lernbereich 7: Integrieren ---------- */
{ id: 'k7-01', m: 7, p: 2, q: String.raw`Welche Stammfunktion hat \(x^n\) für \(n \ne -1\)?`,
  o: [[String.raw`\(\frac{x^{n+1}}{n+1}\)`, 1], [String.raw`\(n\,x^{n-1}\)`, 0], [String.raw`\(x^{n+1}\)`, 0], [String.raw`\(\frac{x^n}{n+1}\)`, 0]],
  why: String.raw`Hochzahl plus 1, dann durch die neue Hochzahl teilen. \(n\,x^{n-1}\) ist die Ableitung.` },
{ id: 'k7-02', m: 7, p: 2, q: String.raw`Welche Stammfunktion hat \(\frac1x\)?`,
  o: [[String.raw`\(\ln|x|\)`, 1], [String.raw`\(-\frac1{x^2}\)`, 0], [String.raw`\(\frac1{x^2}\)`, 0], [String.raw`\(-\frac1x\)`, 0]],
  why: String.raw`Die Potenzregel geht bei \(n = -1\) nicht, man müsste durch 0 teilen. \(\ln|x|\) abgeleitet ergibt \(\frac1x\).` },
{ id: 'k7-03', m: 7, p: 3, q: String.raw`Welche Stammfunktion hat \(\frac1{x^2}\)?`,
  o: [[String.raw`\(-\frac1x\)`, 1], [String.raw`\(\ln(x^2)\)`, 0], [String.raw`\(\frac1x\)`, 0], [String.raw`\(-\frac2{x^3}\)`, 0]],
  why: String.raw`\(x^{-2}\) wird zu \(\frac{x^{-1}}{-1} = -\frac1x\). Ein Logarithmus kommt nur bei \(\frac1x\) heraus.` },
{ id: 'k7-04', m: 7, p: 2, q: String.raw`Welche Stammfunktion hat \(\sin x\)?`,
  o: [[String.raw`\(-\cos x\)`, 1], [String.raw`\(\cos x\)`, 0], [String.raw`\(-\sin x\)`, 0], [String.raw`\(\sin x\)`, 0]],
  why: String.raw`Kontrolle durch Ableiten: \((-\cos x)' = \sin x\).` },
{ id: 'k7-05', m: 7, p: 3, q: String.raw`Welche Stammfunktion hat \(e^{ax}\) für \(a \ne 0\)?`,
  o: [[String.raw`\(\frac1a e^{ax}\)`, 1], [String.raw`\(a\,e^{ax}\)`, 0], [String.raw`\(e^{ax}\)`, 0], [String.raw`\(\frac{e^{ax+1}}{ax+1}\)`, 0]],
  why: String.raw`Ableiten von \(\frac1ae^{ax}\) gibt \(\frac1a\cdot a\,e^{ax} = e^{ax}\). Die Potenzregel gilt hier nicht.` },
{ id: 'k7-06', m: 7, p: 3, q: String.raw`\(\int_2^4 e^2\,dx = \) ?`,
  o: [[String.raw`\(2e^2\)`, 1], [String.raw`\(e^2\)`, 0], [String.raw`\(e^4 - e^2\)`, 0], [String.raw`\(0\)`, 0]],
  why: String.raw`\(e^2\) ist eine Zahl. Konstante mal Intervalllänge: \(e^2\cdot(4-2)\).` },
{ id: 'k7-07', m: 7, p: 2, q: String.raw`Was machst du vor dem Integrieren mit \(\frac{x^2 - 9}{x - 3}\)?`,
  o: [[String.raw`kürzen zu \(x + 3\)`, 1], [String.raw`kürzen zu \(x - 3\)`, 0], ['die Quotientenregel anwenden', 0], ['Zähler und Nenner einzeln integrieren', 0]],
  why: String.raw`\(x^2 - 9 = (x-3)(x+3)\). Das kam fast in jeder Klausur. Beim Integrieren gibt es keine Quotientenregel.` },
{ id: 'k7-08', m: 7, p: 4, q: String.raw`\(\frac{x^2 - 16}{-x + 4} = \) ?`,
  o: [[String.raw`\(-(x+4)\)`, 1], [String.raw`\(x + 4\)`, 0], [String.raw`\(x - 4\)`, 0], [String.raw`\(-(x-4)\)`, 0]],
  why: String.raw`\(-x + 4 = -(x-4)\) und \(x^2 - 16 = (x-4)(x+4)\). Es bleibt \(\frac{x+4}{-1}\). Juli 2023.` },
{ id: 'k7-09', m: 7, p: 2, t: 'num', q: String.raw`\(\int_0^1 2x\,dx = \) ?`, a: 1, show: '1', why: String.raw`\(\left[x^2\right]_0^1 = 1 - 0 = 1\).` },
{ id: 'k7-10', m: 7, p: 3, t: 'num', q: String.raw`\(\int_1^e \frac1x\,dx = \) ?`, a: 1, show: '1', why: String.raw`\(\left[\ln x\right]_1^e = \ln e - \ln 1 = 1 - 0\).` },
{ id: 'k7-11', m: 7, p: 4, t: 'num', q: String.raw`\(\int_2^4 |x-3|\,dx = \) ?`, a: 1, show: '1',
  tip: 'An der Knickstelle aufteilen oder als Fläche denken.',
  why: String.raw`An der Knickstelle 3 aufteilen: zwei Dreiecke mit Grundseite 1 und Höhe 1, jedes \(\frac12\). Juli 2020.` },
{ id: 'k7-12', m: 7, p: 2, q: 'Welcher Fehler passiert beim Einsetzen der Grenzen am häufigsten?',
  o: [['Die Klammer um den Wert der unteren Grenze fehlt.', 1], ['Obere und untere Grenze werden vertauscht.', 0], [String.raw`Die Konstante \(C\) wird vergessen.`, 0], ['Die Grenzen werden in die Ableitung eingesetzt.', 0]],
  why: String.raw`\(F(b) - F(a)\): Das Minus gilt für alles in \(F(a)\). Also \(-\left(\frac12 - 3\right)\), nicht \(-\frac12 - 3\). Beim bestimmten Integral fällt \(C\) weg.` },
{ id: 'k7-13', m: 7, p: 3, q: String.raw`\(\int_{-1}^0\frac1{x+2}\,dx = \) ?`,
  o: [[String.raw`\(\ln 2\)`, 1], [String.raw`\(-\ln 2\)`, 0], [String.raw`\(0\)`, 0], [String.raw`\(\frac12\)`, 0]],
  why: String.raw`\(\left[\ln|x+2|\right]_{-1}^0 = \ln 2 - \ln 1 = \ln 2\). Okt 2020.` },
{ id: 'k7-14', m: 7, p: 3, q: String.raw`Wie teilst du \(\frac{x+2}{x^2}\) zum Integrieren auf?`,
  o: [[String.raw`\(\frac1x + \frac2{x^2}\)`, 1], [String.raw`\(\frac1x + 2\)`, 0], [String.raw`\(\frac3x\)`, 0], [String.raw`\(x + \frac2{x^2}\)`, 0]],
  why: String.raw`Jeden Summanden im Zähler einzeln durch den Nenner: \(\frac{x}{x^2} + \frac{2}{x^2}\). Sep 2024.` },
{ id: 'k7-15', m: 7, p: 4, t: 'num', q: String.raw`Für welches \(k\) gilt \(\int_1^2 kx\,dx = 3\)?`, a: 2, show: '2',
  why: String.raw`\(k\left[\frac{x^2}2\right]_1^2 = k\left(2 - \frac12\right) = \frac32k = 3\), also \(k = 2\).` },
{ id: 'k7-16', m: 7, p: 5, q: String.raw`\(\dfrac{4 - 2x}{\frac1x - \frac12} = \) ?`,
  o: [[String.raw`\(4x\)`, 1], [String.raw`\(2x\)`, 0], [String.raw`\(\frac4x\)`, 0], [String.raw`\((4-2x)\,x\)`, 0]],
  tip: String.raw`Bring den Nenner auf einen Bruch: \(\frac1x - \frac12 = \frac{2-x}{2x}\).`,
  why: String.raw`\(4 - 2x = 2(2-x)\). Durch den Bruch teilen heißt mit dem Kehrwert malnehmen: \(2(2-x)\cdot\frac{2x}{2-x} = 4x\). Juli 2022.` },

/* ---------- Lernbereich 8: Vektoren ---------- */
{ id: 'k8-01', m: 8, p: 2, t: 'num', q: String.raw`Wie lang ist \(\begin{pmatrix}0\\ \sqrt3\\ -1\end{pmatrix}\)?`, a: 2, show: '2',
  why: String.raw`\(\sqrt{0 + 3 + 1} = 2\). Sep 2021.` },
{ id: 'k8-02', m: 8, p: 2, q: String.raw`\(a\cdot b = 0\) bedeutet …`,
  o: [[String.raw`\(a\) und \(b\) stehen senkrecht aufeinander.`, 1], [String.raw`\(a\) und \(b\) sind parallel.`, 0], [String.raw`\(a\) und \(b\) sind gleich lang.`, 0], [String.raw`\(a = b\)`, 0]],
  why: 'Orthogonal heißt Skalarprodukt 0, für Vektoren, die nicht der Nullvektor sind.' },
{ id: 'k8-03', m: 8, p: 2, t: 'num', q: String.raw`\(\begin{pmatrix}1\\2\\3\end{pmatrix}\cdot\begin{pmatrix}4\\-5\\6\end{pmatrix} = \) ?`, a: 12, show: '12',
  why: String.raw`\(4 - 10 + 18 = 12\). Das Skalarprodukt ist eine Zahl, kein Vektor.` },
{ id: 'k8-04', m: 8, p: 2, q: String.raw`Du brauchst einen Vektor, der auf \(a\) und auf \(b\) senkrecht steht. Was rechnest du?`,
  o: [[String.raw`\(a\times b\)`, 1], [String.raw`\(a\cdot b\)`, 0], [String.raw`\(a + b\)`, 0], [String.raw`\(a - b\)`, 0]],
  why: 'Das Kreuzprodukt steht senkrecht auf beiden. Das Skalarprodukt ist nur eine Zahl.' },
{ id: 'k8-05', m: 8, p: 3, q: String.raw`\(\begin{pmatrix}1\\0\\0\end{pmatrix}\times\begin{pmatrix}0\\1\\0\end{pmatrix} = \) ?`,
  o: [[String.raw`\((0,\ 0,\ 1)\)`, 1], [String.raw`\((0,\ 0,\ -1)\)`, 0], [String.raw`\((1,\ 1,\ 0)\)`, 0], [String.raw`\((0,\ 0,\ 0)\)`, 0]],
  why: String.raw`Dritte Komponente: \(a_1b_2 - a_2b_1 = 1\cdot1 - 0\cdot0 = 1\). Die anderen beiden sind 0.` },
{ id: 'k8-06', m: 8, p: 3, q: String.raw`\(b\times a = \) ?`,
  o: [[String.raw`\(-(a\times b)\)`, 1], [String.raw`\(a\times b\)`, 0], [String.raw`\(a\cdot b\)`, 0], ['der Nullvektor', 0]],
  why: 'Beim Kreuzprodukt zählt die Reihenfolge. Vertauschen dreht das Vorzeichen.' },
{ id: 'k8-07', m: 8, p: 3, q: String.raw`\(\cos\varphi = -\frac12\). Welchen Winkel \(\varphi\) schließen die Vektoren ein?`,
  o: [[String.raw`\(\frac{2\pi}3\)`, 1], [String.raw`\(\frac\pi3\)`, 0], [String.raw`\(\frac{5\pi}6\)`, 0], [String.raw`\(\frac{4\pi}3\)`, 0]],
  why: String.raw`Winkel zwischen Vektoren liegen zwischen 0 und \(\pi\). \(\cos\frac{2\pi}3 = -\frac12\). \(\frac{4\pi}3\) ist größer als \(\pi\). Nov 2020.` },
{ id: 'k8-08', m: 8, p: 4, q: String.raw`Welche Vektoren stehen senkrecht auf \((5,\ 3,\ 1)\)?`,
  o: [[String.raw`\((0,\ 1,\ -3)\)`, 1], [String.raw`\((3,\ -5,\ 0)\)`, 1], [String.raw`\((1,\ 0,\ -5)\)`, 1], [String.raw`\((1,\ 1,\ 1)\)`, 0]],
  why: String.raw`Skalarprodukt prüfen: \(0 + 3 - 3 = 0\), \(15 - 15 + 0 = 0\), \(5 + 0 - 5 = 0\), aber \(5 + 3 + 1 = 9\). Juli 2022.` },
{ id: 'k8-09', m: 8, p: 2, q: String.raw`Wie lautet eine Gerade durch die Punkte \(A\) und \(B\)?`,
  o: [[String.raw`\(\vec x = A + \lambda(B - A)\)`, 1], [String.raw`\(\vec x = A + \lambda B\)`, 0], [String.raw`\(\vec x = \lambda(A + B)\)`, 0], [String.raw`\(\vec x = B - \lambda A\)`, 0]],
  why: String.raw`Stützvektor ist ein Punkt, die Richtung ist die Verbindung \(\vec{AB} = B - A\).` },
{ id: 'k8-10', m: 8, p: 3, q: String.raw`Punktprobe: Zeile 1 ergibt \(\lambda = \frac45\), Zeile 2 ergibt \(\lambda = \frac13\). Was folgt daraus?`,
  o: [['Der Punkt liegt nicht auf der Geraden.', 1], ['Der Punkt liegt auf der Geraden.', 0], [String.raw`Man nimmt den Mittelwert der beiden \(\lambda\).`, 0], ['Zeile 3 entscheidet.', 0]],
  why: String.raw`Ein Punkt liegt nur drauf, wenn in jeder Zeile dasselbe \(\lambda\) herauskommt. Ein Widerspruch reicht. Juli 2022.` },
{ id: 'k8-11', m: 8, p: 2, q: String.raw`Welcher Vektor ist ein Normalenvektor der Ebene \(\vec x = \vec p + \lambda\vec u + \mu\vec v\)?`,
  o: [[String.raw`\(\vec u\times\vec v\)`, 1], [String.raw`\(\vec u\cdot\vec v\)`, 0], [String.raw`\(\vec u + \vec v\)`, 0], [String.raw`\(\vec p\times\vec u\)`, 0]],
  why: 'Der Normalenvektor steht senkrecht auf beiden Richtungen, also das Kreuzprodukt der Richtungsvektoren.' },
{ id: 'k8-12', m: 8, p: 3, q: String.raw`Welche Gerade durch \((1, 2, 3)\) ist parallel zur \(x\)-\(y\)-Ebene?`,
  o: [[String.raw`\(\vec x = (1,2,3) + \lambda(1,0,0)\)`, 1], [String.raw`\(\vec x = (1,2,3) + \lambda(0,0,1)\)`, 0], [String.raw`\(\vec x = (1,2,3) + \lambda(1,1,1)\)`, 0], [String.raw`\(\vec x = \lambda(1,2,3)\)`, 0]],
  why: String.raw`Parallel zur \(x\)-\(y\)-Ebene heißt: keine Bewegung in \(z\)-Richtung, dritte Komponente der Richtung 0. Juli 2023.` },
{ id: 'k8-13', m: 8, p: 3, q: String.raw`Zwei Geraden haben die Richtungsvektoren \((2, -6, -4)\) und \((-3, 9, 6)\). Was gilt?`,
  o: [['Die Richtungen sind Vielfache voneinander, die Geraden sind parallel oder identisch.', 1], ['Die Geraden stehen senkrecht aufeinander.', 0], ['Die Geraden sind windschief.', 0], ['Die Geraden schneiden sich.', 0]],
  why: String.raw`\((-3, 9, 6) = -\frac32(2, -6, -4)\). Danach Punktprobe: Liegt der Stützpunkt der einen auf der anderen, sind sie identisch. Nov 2024.` },
{ id: 'k8-14', m: 8, p: 3, t: 'num', q: String.raw`\(\vec n = (-3, -4, -1)\), \(\vec p = (1, -2, 1)\). Wie groß ist \(d = \vec n\cdot\vec p\) in der Koordinatenform?`, a: 4, show: '4',
  why: String.raw`\(-3 + 8 - 1 = 4\), also \(-3x_1 - 4x_2 - x_3 = 4\). Nov 2024.` },
{ id: 'k8-15', m: 8, p: 3, q: String.raw`Für welche \(c\) hat \(\begin{pmatrix}c\\3\end{pmatrix}\) die Länge 5?`,
  o: [[String.raw`\(c = \pm4\)`, 1], [String.raw`\(c = 4\)`, 0], [String.raw`\(c = \pm2\)`, 0], [String.raw`\(c = \pm\sqrt{34}\)`, 0]],
  why: String.raw`\(\sqrt{c^2 + 9} = 5 \iff c^2 = 16\). Beide Vorzeichen. Sep 2022.` },
{ id: 'k8-16', m: 8, p: 4, q: String.raw`\((1,\ 0,\ 3)\times(-2,\ 1,\ 4) = \) ?`,
  o: [[String.raw`\((-3,\ -10,\ 1)\)`, 1], [String.raw`\((3,\ 10,\ -1)\)`, 0], [String.raw`\((-3,\ 10,\ 1)\)`, 0], [String.raw`\((3,\ -10,\ 1)\)`, 0]],
  tip: 'Erste Zeile: Zeilen 2 und 3 über Kreuz. Zweite Zeile: Zeilen 3 und 1. Dritte Zeile: Zeilen 1 und 2.',
  why: String.raw`Zeile 1: \(0\cdot4 - 3\cdot1 = -3\). Zeile 2: \(3\cdot(-2) - 1\cdot4 = -10\). Zeile 3: \(1\cdot1 - 0\cdot(-2) = 1\). Kontrolle: \((1,0,3)\cdot(-3,-10,1) = -3 + 0 + 3 = 0\).` },
);
