MODS.P = {
  intro: String.raw`<p>Zwei echte Klausuren, die in keinem Modul vorkommen. Schreib sie wie die echte: 60 Minuten Timer, Kuli, kein Taschenrechner, Handy weg, Tabelle vom Deckblatt ist erlaubt. Erst wenn die Zeit um ist, die Lösungen aufdecken und dir ehrlich Punkte geben. Halbe Punkte sind okay.</p>
  <p>Danach: Jede Aufgabe unter 4 Punkten zeigt dir, welches Modul du am Folgetag noch einmal aufmachst. Schick mir gern Fotos deiner Lösungen, dann korrigiere ich wie der Prof.</p>`,
  exams: [
    { id: '2025-11', nav: 'November 2025', day: 'Freitag, 2. Oktober', title: 'Klausur vom 28. November 2025',
      tasks: [
        { m: 1,
          q: String.raw`<p>Wir betrachten die Funktion \(\displaystyle f(x) = 2\cos\left(-\frac{\pi x}2\right) - \ln\left(\frac1e\right)\).</p><p>Bestimmen Sie den maximalen Definitionsbereich, vereinfachen Sie die Funktionsvorschrift und zeichnen Sie den Graphen. Eventuelle Asymptoten sind mit einzuzeichnen.</p>`,
          s: [String.raw`\(\ln\frac1e = -1\) und \(\cos(-u) = \cos u\), also \(f(x) = 2\cos\left(\frac{\pi x}2\right) + 1\). \(\ D = \mathbb R\).`,
            String.raw`Periode: \(\frac{2\pi}{\pi/2} = 4\). Amplitude 2, um 1 nach oben: Werte zwischen \(-1\) und \(3\).`,
            String.raw`Hochpunkte \((0|3)\), \((\pm4|3)\). Tiefpunkte \((\pm2|-1)\). \(f(\pm1) = 1\).`,
            String.raw`Nullstellen: \(\cos\frac{\pi x}2 = -\frac12 \iff \frac{\pi x}2 = \pm\frac{2\pi}3 + 2k\pi \iff x = \pm\frac43 + 4k\). Keine Asymptoten.`],
          r: String.raw`\(f(x) = 2\cos\left(\frac{\pi x}{2}\right) + 1\), \(D = \mathbb R\), keine Asymptoten`,
          plot: { curves: [{ f: x => 2 * Math.cos(Math.PI * x / 2) + 1 }], pts: [{ x: 0, y: 3, l: '(0|3)' }, { x: 2, y: -1, l: '(2|−1)', dy: 16 }, { x: -2, y: -1, l: '(−2|−1)', dy: 16, anchor: 'end', dx: -6 }, { x: 4, y: 3 }, { x: -4, y: 3 }, { x: 4 / 3, y: 0 }, { x: -4 / 3, y: 0 }] } },
        { m: 2,
          q: String.raw`<p>Bestimmen Sie die Lösung(en) der Gleichung</p><div class="fbig">\[\frac{2 - |x+3|}{|2x| - 2} = 1.\]</div>`,
          s: [String.raw`\(D\): \(|2x| \ne 2 \iff x \ne \pm1\).`,
            String.raw`Mal Nenner: \(2 - |x+3| = 2|x| - 2 \iff |x+3| + 2|x| = 4\).`,
            String.raw`Fall \(x \lt -3\): \(-x - 3 - 2x = 4 \iff x = -\frac73\) ✗`,
            String.raw`Fall \(-3 \le x \lt 0\): \(x + 3 - 2x = 4 \iff x = -1\). Nicht in \(D\) ✗`,
            String.raw`Fall \(x \ge 0\): \(x + 3 + 2x = 4 \iff x = \frac13\) ✓`],
          r: String.raw`\(L = \left\{\frac13\right\}\)` },
        { m: 3,
          q: String.raw`<p>Wir betrachten \(\displaystyle f(x) = \frac{4x^3 - 36x}{x^3 - 4x^2 + 4x}\).</p><p>(a) Maximaler Definitionsbereich, Art der Lücken (hebbar, Pol mit oder ohne Vorzeichenwechsel). (b) Asymptote für \(x \to \pm\infty\).</p>`,
          s: [String.raw`Zähler \(4x(x-3)(x+3)\), Nenner \(x(x-2)^2\). \(\ D = \mathbb R\setminus\{0, 2\}\).`,
            String.raw`Gekürzt: \(f(x) = \frac{4(x-3)(x+3)}{(x-2)^2}\) für \(x \ne 0\).`,
            String.raw`\(x = 0\): <b>hebbare Lücke</b>. \(\ x = 2\): \((x-2)^2\) bleibt, Zähler dort \(-20 \ne 0\), <b>Pol ohne Vorzeichenwechsel</b>.`,
            String.raw`(b) Zähler und Nenner haben Grad 2, Vorfaktoren 4 und 1: Asymptote \(y = 4\).`],
          r: String.raw`\(D = \mathbb R\setminus\{0, 2\}\), hebbar bei 0, Pol ohne VZW bei 2, Asymptote \(y = 4\)` },
        { m: 4,
          q: String.raw`<p>Für \(a \in \mathbb R\) sei \(\displaystyle f(x) = \frac12\big(\log_3(x-1) + \log_3(x+1)\big) - \log_3(x-a)\).</p><p>(a) Maximaler Definitionsbereich in Abhängigkeit von \(a\). (b) Nullstelle(n) für \(a = \frac12\).</p>`,
          s: [String.raw`(a) \(x \gt 1\), \(x \gt -1\), \(x \gt a\). Zusammen \(x \gt \max\{1, a\}\).`,
            String.raw`(b) \(a = \frac12\): \(D = (1, \infty)\). \(\ f(x) = \log_3\sqrt{x^2-1} - \log_3\left(x - \frac12\right)\).`,
            String.raw`\(f = 0 \iff \sqrt{x^2-1} = x - \frac12\). Quadrieren: \(x^2 - 1 = x^2 - x + \frac14 \iff x = \frac54\).`,
            String.raw`Probe: \(\sqrt{\frac{25}{16} - 1} = \frac34 = \frac54 - \frac12\) ✓`],
          r: String.raw`(a) \(D = (\max\{1,a\}, \infty)\) &nbsp; (b) \(x = \frac54\)` },
        { m: 5,
          q: String.raw`<p>Berechnen Sie die Lösung(en):</p><p>(a) \(\displaystyle \cos\left(\frac x6\right) = \sin\left(-\frac\pi6\right)\) &nbsp; (b) \(\displaystyle \sin(2x - 5) = \frac1{\pi^{-1}}\)</p>`,
          s: [String.raw`(a) \(\sin(-\frac\pi6) = -\frac12\). \(\ \frac x6 = \pm\frac{2\pi}3 + 2k\pi \iff x = \pm4\pi + 12k\pi\).`,
            String.raw`(b) \(\frac1{\pi^{-1}} = \pi \gt 1\): \(L = \emptyset\).`],
          r: String.raw`(a) \(x = \pm4\pi + 12k\pi\), \(k \in \mathbb Z\) &nbsp; (b) \(L = \emptyset\)` },
        { m: 6,
          q: String.raw`<p>Berechnen Sie die Ableitung von</p><div class="fbig">\[f(x) = \frac{e^x\ln(x)}{4x^2} - \sqrt{2x^3+1}.\]</div>`,
          s: [String.raw`\(D\): \(x \gt 0\).`,
            String.raw`Quotientenregel: \(u = e^x\ln x\), \(u' = e^x\ln x + \frac{e^x}x\). \(\ v = 4x^2\), \(v' = 8x\).`,
            String.raw`\(\frac{(e^x\ln x + \frac{e^x}x)4x^2 - e^x\ln x\cdot8x}{16x^4} = \frac{e^x(4x^2\ln x + 4x - 8x\ln x)}{16x^4} = \frac{e^x(x\ln x - 2\ln x + 1)}{4x^3}\).`,
            String.raw`\(\left(\sqrt{2x^3+1}\right)' = \frac{6x^2}{2\sqrt{2x^3+1}} = \frac{3x^2}{\sqrt{2x^3+1}}\).`],
          r: String.raw`\(f'(x) = \frac{e^x\left(x\ln x - 2\ln x + 1\right)}{4x^3} - \frac{3x^2}{\sqrt{2x^3+1}}\)` },
        { m: 7,
          q: String.raw`<p>Für welches \(a \in \mathbb R\), \(a \gt 1\), gilt</p><div class="fbig">\[\int_1^a \frac{1+2x}{2x} - 1\,dx = \int_{-\pi}^0 \cos(x) + \sqrt{4^2 + 3^2}\,dx\ ?\]</div>`,
          s: [String.raw`Links: \(\frac{1+2x}{2x} - 1 = \frac1{2x} + 1 - 1 = \frac1{2x}\). \(\ \int_1^a \frac1{2x}\,dx = \frac12\ln a\).`,
            String.raw`Rechts: \(\sqrt{25} = 5\). \(\ [\sin x + 5x]_{-\pi}^0 = 0 - (0 - 5\pi) = 5\pi\).`,
            String.raw`\(\frac12\ln a = 5\pi \iff a = e^{10\pi}\).`],
          r: String.raw`\(a = e^{10\pi}\)` },
        { m: 8,
          q: String.raw`<p>\(a = \begin{pmatrix}-4\\0\\-3\end{pmatrix}\), \(\ b = \begin{pmatrix}1\\ \sqrt{-2y}\\ y\end{pmatrix}\), \(y \in \mathbb R\), \(y \lt 0\).</p><p>(a) Für welches \(y \lt 0\) schließen \(a\) und \(b\) einen Winkel von \(\frac\pi3\) ein? (b) Sei \(y = -2\). Bestimmen Sie einen Vektor \(c\), der auf \(a\) und \(b\) senkrecht steht.</p>`,
          s: [String.raw`(a) \(|a| = 5\). \(\ |b| = \sqrt{1 - 2y + y^2} = |1 - y| = 1 - y\) (weil \(y \lt 0\)). \(\ a\cdot b = -4 - 3y\).`,
            String.raw`\(\frac{-4-3y}{5(1-y)} = \frac12 \iff -8 - 6y = 5 - 5y \iff y = -13\). Kontrolle: \(\frac{35}{70} = \frac12\) ✓`,
            String.raw`(b) \(b = (1, 2, -2)\). \(\ c = a\times b = (0\cdot(-2) - (-3)\cdot2,\ (-3)\cdot1 - (-4)(-2),\ (-4)\cdot2 - 0) = (6, -11, -8)\).`,
            String.raw`Kontrolle: \(a\cdot c = -24 + 24 = 0\), \(b\cdot c = 6 - 22 + 16 = 0\) ✓`],
          r: String.raw`(a) \(y = -13\) &nbsp; (b) \(c = (6, -11, -8)\)` },
      ] },
    { id: '2026-02', nav: 'Februar 2026', day: 'Samstag, 3. Oktober', title: 'Klausur vom 2. Februar 2026',
      tasks: [
        { m: 1,
          q: String.raw`<p>Wir betrachten \(\displaystyle f(x) = \sqrt{(x-2)^2} + \sin\left(-\frac\pi2\right)\).</p><p>Vereinfachen Sie die Funktionsvorschrift, bestimmen Sie den Definitionsbereich und zeichnen Sie den Graphen. Eventuelle Asymptoten sind mit einzuzeichnen.</p>`,
          s: [String.raw`\(\sqrt{(x-2)^2} = |x-2|\), \(\ \sin(-\frac\pi2) = -1\). Also \(f(x) = |x-2| - 1\), \(D = \mathbb R\).`,
            String.raw`V-Form, um 2 nach rechts, um 1 nach unten. Spitze \((2|-1)\).`,
            String.raw`Nullstellen: \(|x-2| = 1 \iff x = 1\) oder \(x = 3\). Keine Asymptoten.`],
          r: String.raw`\(f(x) = |x-2| - 1\), \(D = \mathbb R\), keine Asymptoten`,
          plot: { curves: [{ f: x => Math.abs(x - 2) - 1 }], pts: [{ x: 2, y: -1, l: '(2|−1)', dy: 16 }, { x: 1, y: 0 }, { x: 3, y: 0 }] } },
        { m: 2,
          q: String.raw`<p>Bestimmen Sie die Lösungsmenge der Ungleichung</p><div class="fbig">\[x + \left(5^{-1} + 20^{-1}\right)^{-1} \le 2|x-1|.\]</div>`,
          s: [String.raw`\(\frac15 + \frac1{20} = \frac14\), Kehrwert 4. Also \(x + 4 \le 2|x-1|\).`,
            String.raw`Fall \(x \ge 1\): \(x + 4 \le 2x - 2 \iff x \ge 6\).`,
            String.raw`Fall \(x \lt 1\): \(x + 4 \le 2 - 2x \iff x \le -\frac23\).`],
          r: String.raw`\(L = \left(-\infty, -\frac23\right] \cup [6, \infty)\)` },
        { m: 3,
          q: String.raw`<p>Bestimmen Sie den maximalen Definitionsbereich und die Nullstellen von</p><div class="fbig">\[f(x) = 1 - \sqrt{\sqrt x - 2}.\]</div>`,
          s: [String.raw`\(x \ge 0\) und \(\sqrt x - 2 \ge 0 \iff x \ge 4\). \(\ D = [4, \infty)\).`,
            String.raw`\(\sqrt{\sqrt x - 2} = 1 \iff \sqrt x - 2 = 1 \iff \sqrt x = 3 \iff x = 9\) ✓`],
          r: String.raw`\(D = [4, \infty)\), Nullstelle \(x = 9\)` },
        { m: 4,
          q: String.raw`<p>Bestimmen Sie die Lösungsmenge der Gleichung</p><div class="fbig">\[\log_6(x+6) - \log_6(x-2) = \log_6(x+1).\]</div>`,
          s: [String.raw`\(D\): \(x \gt 2\).`,
            String.raw`\(\frac{x+6}{x-2} = x + 1 \iff x + 6 = x^2 - x - 2 \iff x^2 - 2x - 8 = 0 \iff (x-4)(x+2) = 0\).`,
            String.raw`\(x = -2\) liegt nicht in \(D\).`],
          r: String.raw`\(L = \{4\}\)` },
        { m: 5,
          q: String.raw`<p>Berechnen Sie die Lösung(en):</p><p>(a) \(\displaystyle \sin\left(\frac x6\right) = \cos\left(-\frac\pi6\right)\) &nbsp; (b) \(\displaystyle \cos(2x - 5) = \frac1{\pi^{-1}}\)</p>`,
          s: [String.raw`(a) \(\cos(-\frac\pi6) = \frac{\sqrt3}2\). \(\ \frac x6 = \frac\pi3 + 2k\pi\) oder \(\frac{2\pi}3 + 2k\pi\).`,
            String.raw`\(x = 2\pi + 12k\pi\) oder \(x = 4\pi + 12k\pi\).`,
            String.raw`(b) \(\frac1{\pi^{-1}} = \pi \gt 1\): \(L = \emptyset\).`],
          r: String.raw`(a) \(x = 2\pi + 12k\pi\) oder \(x = 4\pi + 12k\pi\) &nbsp; (b) \(L = \emptyset\)` },
        { m: 6,
          q: String.raw`<p>Berechnen Sie den Definitionsbereich und die Ableitung von</p><div class="fbig">\[f(x) = \sin(10) + \cos(e^x) + \frac{2x^2}{\ln(x)}.\]</div>`,
          s: [String.raw`\(D\): \(x \gt 0\) und \(\ln x \ne 0 \iff x \ne 1\). \(\ D = (0, 1) \cup (1, \infty)\).`,
            String.raw`\(\sin 10\) ist eine Zahl. \(\ (\cos e^x)' = -e^x\sin(e^x)\).`,
            String.raw`\(\left(\frac{2x^2}{\ln x}\right)' = \frac{4x\ln x - 2x^2\cdot\frac1x}{(\ln x)^2} = \frac{2x(2\ln x - 1)}{(\ln x)^2}\).`],
          r: String.raw`\(f'(x) = -e^x\sin(e^x) + \frac{2x\left(2\ln x - 1\right)}{(\ln x)^2}\)` },
        { m: 7,
          q: String.raw`<p>Berechnen Sie das Integral</p><div class="fbig">\[\int_1^3 e^2 + \frac{2x^2 - 8}{x+2} + \frac1x\,dx.\]</div>`,
          s: [String.raw`\(\frac{2x^2-8}{x+2} = \frac{2(x-2)(x+2)}{x+2} = 2x - 4\).`,
            String.raw`\(\left[e^2x + x^2 - 4x + \ln x\right]_1^3 = (3e^2 - 3 + \ln 3) - (e^2 - 3 + 0)\).`],
          r: String.raw`\(2e^2 + \ln(3)\)` },
        { m: 8,
          q: String.raw`<p>\(P = \begin{pmatrix}0\\-1\\6\end{pmatrix}\), \(\ E: \vec x = \begin{pmatrix}3\\-1\\4\end{pmatrix} + \lambda\begin{pmatrix}-2\\1\\2\end{pmatrix} + \mu\begin{pmatrix}3\\0\\-2\end{pmatrix}\).</p><p>(a) Liegt \(P\) in \(E\)? (b) Parameterdarstellung einer Geraden \(g\), die durch \(P\) geht und \(E\) senkrecht schneidet.</p>`,
          s: [String.raw`(a) Zeilenweise: \(-1 + \lambda = -1 \Rightarrow \lambda = 0\). \(\ 4 + 2\lambda - 2\mu = 6 \Rightarrow \mu = -1\).`,
            String.raw`Erste Zeile prüfen: \(3 - 2\cdot0 + 3\cdot(-1) = 0\) ✓. \(P\) liegt in \(E\).`,
            String.raw`(b) \(\vec n = (-2,1,2)\times(3,0,-2) = (1\cdot(-2) - 2\cdot0,\ 2\cdot3 - (-2)(-2),\ (-2)\cdot0 - 1\cdot3) = (-2, 2, -3)\).`,
            String.raw`\(g: \vec x = (0, -1, 6) + t\,(-2, 2, -3)\).`],
          r: String.raw`(a) ja, mit \(\lambda = 0\), \(\mu = -1\) &nbsp; (b) \(g: \vec x = (0,-1,6) + t(-2,2,-3)\)` },
      ] },
  ],
};
